"""empty message

Revision ID: 010566aefb55
Revises: 150b61978649
Create Date: 2021-04-23 23:20:30.982190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '010566aefb55'
down_revision = '150b61978649'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'item_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('item_name', sa.VARCHAR(), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False, comment='Item Name'))
    # ### end Alembic commands ###
