"""empty message

Revision ID: 150b61978649
Revises: f9c93bdab6f7
Create Date: 2021-04-23 16:01:03.928235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '150b61978649'
down_revision = 'f9c93bdab6f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('item_category', sa.String(), server_default='', nullable=False, comment='Category Name'))
    op.add_column('items', sa.Column('item_name', sa.String(), server_default='', nullable=False, comment='Item Name'))
    op.add_column('items', sa.Column('item_price', sa.String(), server_default='', nullable=False, comment='Item Price'))
    op.add_column('items', sa.Column('item_subcategory', sa.String(), server_default='', nullable=False, comment='Subcategory Name'))
    op.add_column('items', sa.Column('item_time_description', sa.String(), server_default='', nullable=False, comment='Time Description'))
    op.add_column('items', sa.Column('item_time_quantity', sa.String(), server_default='', nullable=False, comment='Time Quantity'))
    op.drop_column('items', 'price')
    op.drop_column('items', 'name')
    op.drop_column('items', 'data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('data', sa.VARCHAR(), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False, comment='Item ENG Name'))
    op.add_column('items', sa.Column('name', sa.VARCHAR(), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False, comment='Item RU Name'))
    op.add_column('items', sa.Column('price', sa.VARCHAR(), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False, comment='Item Price'))
    op.drop_column('items', 'item_time_quantity')
    op.drop_column('items', 'item_time_description')
    op.drop_column('items', 'item_subcategory')
    op.drop_column('items', 'item_price')
    op.drop_column('items', 'item_name')
    op.drop_column('items', 'item_category')
    # ### end Alembic commands ###
