"""empty message

Revision ID: 665addac7705
Revises: 6b12429b0d5e
Create Date: 2021-04-25 12:22:24.830772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '665addac7705'
down_revision = '6b12429b0d5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
