"""empty message

Revision ID: 6b12429b0d5e
Revises: 010566aefb55
Create Date: 2021-04-24 00:40:44.953171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b12429b0d5e'
down_revision = '010566aefb55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('ordered_category', sa.String(), server_default='', nullable=False, comment='Ordered Item Category'))
    op.add_column('orders', sa.Column('ordered_subcategory', sa.String(), server_default='', nullable=False, comment='Ordered Item Subcategory'))
    op.add_column('orders', sa.Column('ordered_time', sa.String(), server_default='', nullable=False, comment='Ordered Time'))
    op.drop_column('orders', 'ordered_item')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('ordered_item', sa.VARCHAR(), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False, comment='Ordered Item Name RU'))
    op.drop_column('orders', 'ordered_time')
    op.drop_column('orders', 'ordered_subcategory')
    op.drop_column('orders', 'ordered_category')
    # ### end Alembic commands ###
