"""empty message

Revision ID: 88b58467c2f9
Revises: 
Create Date: 2021-04-23 12:14:27.457066

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '88b58467c2f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
    op.create_table('admins',
    sa.Column('telegram_id', sa.String(), nullable=False, comment='Admin Telegram ID'),
    sa.Column('name', sa.String(), server_default='', nullable=False, comment='Admin name'),
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='ID'),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='UTC create datetime'),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='UTC update datetime'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('data', sa.String(), server_default='', nullable=False, comment='Item ENG Name'),
    sa.Column('name', sa.String(), server_default='', nullable=False, comment='Item RU Name'),
    sa.Column('price', sa.String(), server_default='', nullable=False, comment='Item Price'),
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='ID'),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='UTC create datetime'),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='UTC update datetime'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('telegram_id', sa.String(), nullable=True, comment='User Telegram ID'),
    sa.Column('ordered_item', sa.String(), server_default='', nullable=False, comment='Ordered Item Name RU'),
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='ID'),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='UTC create datetime'),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='UTC update datetime'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('name', sa.String(), server_default='', nullable=False, comment='User Name'),
    sa.Column('phone_number', sa.String(), server_default='', nullable=False, comment='User Phone Number'),
    sa.Column('telegram_id', sa.String(), nullable=True, comment='Telegram ID'),
    sa.Column('weight', sa.String(), server_default='', nullable=False, comment='User Weight'),
    sa.Column('height', sa.String(), server_default='', nullable=False, comment='User Height'),
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='ID'),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='UTC create datetime'),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='UTC update datetime'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('orders')
    op.drop_table('items')
    op.drop_table('admins')
    # ### end Alembic commands ###
