"""empty message

Revision ID: a3fe4b6c47c8
Revises: 88b58467c2f9
Create Date: 2021-04-23 13:04:34.753153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3fe4b6c47c8'
down_revision = '88b58467c2f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
