"""empty message

Revision ID: f9c93bdab6f7
Revises: a3fe4b6c47c8
Create Date: 2021-04-23 14:06:00.606070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9c93bdab6f7'
down_revision = 'a3fe4b6c47c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('status', sa.String(), server_default='', nullable=False, comment='Order Status'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'status')
    # ### end Alembic commands ###
